// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFP9J5YzepApMDAvlWLnB_PzI7IwHdKc',
    appId: '1:371987029122:web:60f69c039372847ba1a89b',
    messagingSenderId: '371987029122',
    projectId: 'testing-cli-44c7c',
    authDomain: 'testing-cli-44c7c.firebaseapp.com',
    databaseURL: 'https://testing-cli-44c7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-cli-44c7c.appspot.com',
    measurementId: 'G-TZ2H1NZCQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACL3Y-1P_48fA7qMTwrNMZ9BB_yeuwMTE',
    appId: '1:371987029122:android:b0602187276015f8a1a89b',
    messagingSenderId: '371987029122',
    projectId: 'testing-cli-44c7c',
    databaseURL: 'https://testing-cli-44c7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-cli-44c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMPE8J2Ymjx57El63p8jZENmR8dhTaeE',
    appId: '1:371987029122:ios:f407d7f76ea2bcdea1a89b',
    messagingSenderId: '371987029122',
    projectId: 'testing-cli-44c7c',
    databaseURL: 'https://testing-cli-44c7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-cli-44c7c.appspot.com',
    iosBundleId: 'com.gectcr.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUMPE8J2Ymjx57El63p8jZENmR8dhTaeE',
    appId: '1:371987029122:ios:6102828d032eac80a1a89b',
    messagingSenderId: '371987029122',
    projectId: 'testing-cli-44c7c',
    databaseURL: 'https://testing-cli-44c7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-cli-44c7c.appspot.com',
    iosBundleId: 'com.gectcr.firebaseproject.RunnerTests',
  );
}
